# Automations
# automations.yaml
# 2021-06-13

# Zeitschalter Wochentags HZ ###################################################
  - alias: 'HZ Timer Wochentags ein'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_hz_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'on'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.hzp_wd_mo_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_wd_mi_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_wd_ab_on.state == states.sensor.time.state }}'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.hz_absenkung
      - service: logbook.log
        data_template:
          name: Heizung Zeitschalter WD
          message: normal 

  - alias: 'HZ Timer Wochentags aus'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_hz_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'on'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.hzp_wd_mo_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_wd_mi_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_wd_ab_off.state == states.sensor.time.state }}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.hz_absenkung
      - service: logbook.log
        data_template:
          name: Heizung Zeitschalter WD
          message: abgesenkt
# Zeitschalter Wochentags HZ ENDE ##############################################

# Zeitschalter Wochenende HZ ###################################################
  - alias: 'HZ Timer Wochenende ein'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_hz_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'off'
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.hzp_we_mo_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_we_mi_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_we_ab_on.state == states.sensor.time.state }}'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.hz_absenkung
      - service: logbook.log
        data_template:
          name: Heizung Zeitschalter WE
          message: normal 
          
  - alias: 'HZ Timer Wochenende aus'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_hz_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'off'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.hzp_we_mo_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_we_mi_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.hzp_we_ab_off.state == states.sensor.time.state }}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.hz_absenkung
      - service: logbook.log
        data_template:
          name: Heizung Zeitschalter WE
          message: abgesenkt
# Zeitschalter Wochenende HZ ENDE ##############################################

# Zeitschalter HZ Pumpe ########################################################
  - alias: 'HZ Pumpe Timer ein'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.hz_umw_main
          state: 'on'
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.hz_aussentemp_ein
            state: 'on'
          - condition: template
            value_template: '{{ states.input_select.hzp_on.state == states.sensor.time.state }}'
    action:
      - service: switch.turn_on
        entity_id: switch.hzp
#      - service: logbook.log
#        data_template:
#          name: HZPumpe Zeitschalter
#          message: ein

  - alias: 'HZ Pumpe Timer aus'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.hz_umw_main
          state: 'off'
        - condition: template
          value_template: '{{ states.input_select.hzp_off.state == states.sensor.time.state }}' 
    action:
      - service: switch.turn_off
        entity_id: switch.hzp
      - service: logbook.log
        data_template:
          name: HZPumpe Zeitschalter
          message: aus
# Zeitschalter HZ Pumpe ENDE ###################################################


# Änderung Solltemperatur HZ ###################################################
  - alias: 'Aenderung HZ Thermostate Solltemperatur'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_number.hz_solltemp
    action:
      - service: climate.set_temperature
        entity_id: climate.hz_plus_thermostat
        data_template:
          temperature: '{{ states.input_number.hz_solltemp.state }}'
      - service: climate.set_temperature
        entity_id: climate.hz_minus_thermostat 
        data_template:
          temperature: '{{ states.input_number.hz_solltemp.state }}'
# Änderung Solltemperatur HZ ENDE ##############################################

# Änderung Solltemperatur HZ nach Aussentemp normal ############################
  - alias: 'Aenderung HZ Solltemperatur Aussentemp normal'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.wetterdaten_temperature
      - platform: state
        entity_id: input_boolean.hz_absenkung
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.hz_absenkung
            state: 'off'
          - condition: state
            entity_id: input_boolean.hz_main
            state: 'on'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.hz_solltemp
          value: >
            {{ states.sensor.hz_vorl_temp.state }}
# Änderung Solltemperatur HZ normal ENDE #######################################

# Änderung Solltemperatur HZ nach Aussentemp abgesenkt #########################
  - alias: 'Aenderung HZ Solltemperatur Aussentemp abgesenkt'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.wetterdaten_temperature
      - platform: state
        entity_id: input_boolean.hz_absenkung
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.hz_absenkung
            state: 'on'
          - condition: state
            entity_id: input_boolean.hz_main
            state: 'on'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.hz_solltemp
          value: >
            {{ states.sensor.hz_vorl_temp.state | float / 100.0 * states.input_number.hz_absenk.state | float}}
# Änderung Solltemperatur HZ abgesenkt ENDE ####################################

# Heizung aktivieren (Aussentemp) ##############################################
  - alias: 'HZ aktivieren'
    initial_state: true
    trigger:
    - platform: state
      entity_id: binary_sensor.hz_aussentemp_ein
      to: 'on'
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.enable_hz_timer
    - service: logbook.log
      data_template:
        name: Heizung
        message: aktiv (AussenTemp.)
# Heizung aktivieren (Aussentemp) Ende #########################################

# Heizung De-aktivieren (Aussentemp) ###########################################
  - alias: 'HZ de-aktivieren'
    initial_state: true
    trigger:
    - platform: state
      entity_id: binary_sensor.hz_aussentemp_ein
      to: 'off'
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.enable_hz_timer 
    - service: switch.turn_off
      entity_id: switch.hzp
    - service: logbook.log
      data_template:
        name: Heizung
        message: aus (AussenTemp.)
# Heizung De-aktivieren (Aussentemp) Ende ######################################

# HZ Regler max begrenzen (Ventil) #################################################
  - alias: HZ Regler begrenzen
    initial_state: true
    trigger:
    - platform: template
      value_template: '{{ states.sensor.hz_stand_ventil.state | float > states.input_number.hz_ventil_max.state | float}}'
    action:
    - service: climate.turn_off
      entity_id: climate.hz_plus_thermostat
# HZ Regler begrenzen (Ventil) Ende ############################################
      
# HZ Regler max freigeben (Ventil) #################################################
  - alias: HZ Regler freigeben
    initial_state: true
    trigger:
    - platform: template
      value_template: '{{ states.sensor.hz_stand_ventil.state | float <= states.input_number.hz_ventil_max.state | float}}'
    action:
    - service: climate.turn_on
      entity_id: climate.hz_plus_thermostat
# HZ Regler freigeben (Ventil) Ende ############################################

# HZ Regler min begrenzen (Ventil) #################################################
  - alias: HZ Regler min begrenzen
    initial_state: true
    trigger:
    - platform: template
      value_template: '{{ states.sensor.hz_stand_ventil.state | float < states.input_number.hz_ventil_min.state | float}}'
    action:
    - service: climate.turn_off
      entity_id: climate.hz_minus_thermostat
# HZ Regler begrenzen (Ventil) Ende ############################################
      
# HZ Regler min freigeben (Ventil) #################################################
  - alias: HZ Regler min freigeben
    initial_state: true
    trigger:
    - platform: template
      value_template: '{{ states.sensor.hz_stand_ventil.state | float >= states.input_number.hz_ventil_min.state | float}}'
    action:
    - service: climate.turn_on
      entity_id: climate.hz_minus_thermostat
# HZ Regler freigeben (Ventil) Ende ############################################

# Zeitschalter Wochentags Umwälzpumpe ##########################################
  - alias: 'WW Umwaelzpumpe Timer Wochentags ein'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_zirk_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'on'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.wwp_wd_mo_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_wd_mi_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_wd_ab_on.state == states.sensor.time.state }}'
    action:
      - service: switch.turn_on
        entity_id: switch.wwp
      - service: logbook.log
        data_template:
          name: WWPumpe Timer
          message: WDein

  - alias: 'WW Umwaelzpumpe Timer Wochentags aus'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_zirk_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'on'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.wwp_wd_mo_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_wd_mi_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_wd_ab_off.state == states.sensor.time.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.wwp
      - service: logbook.log
        data_template:
          name: WWPumpe Timer
          message: WDaus
# Zeitschalter Wochentags Umwälzpumpe ENDE #####################################

# Zeitschalter Wochenende Umwälzpumpe ##########################################
  - alias: 'WW Umwaelzpumpe Timer Wochenende ein'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_zirk_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'off'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.wwp_we_mo_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_we_mi_on.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_we_ab_on.state == states.sensor.time.state }}'
    action:
      - service: switch.turn_on
        entity_id: switch.wwp
      - service: logbook.log
        data_template:
          name: WWPumpe Timer
          message: WEein

  - alias: 'WW Umwaelzpumpe Timer Wochenende aus'
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
        seconds: '0'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.enable_zirk_timer
            state: 'on'
          - condition: state
            entity_id: binary_sensor.wochentag
            state: 'off'    
          - condition: or
            conditions:
              - condition: template
                value_template: '{{ states.input_select.wwp_we_mo_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_we_mi_off.state == states.sensor.time.state }}'
              - condition: template
                value_template: '{{ states.input_select.wwp_we_ab_off.state == states.sensor.time.state }}'
    action:
      - service: switch.turn_off
        entity_id: switch.wwp
      - service: logbook.log
        data_template:
          name: WWPumpe Timer
          message: WEaus
# Zeitschalter Wochenende Umwälzpumpe ENDE #####################################

# Zeitschalter Sommerbetrieb ###################################################
  - alias: 'HZP Sommerbetrieb ein'
    initial_state: true
    trigger:
      - platform: time_pattern
        hours: '11'
        minutes: '55'
        seconds: '0'
    condition:
      - condition: time
        weekday:
         - sat
    action:
    - service: switch.turn_on
      entity_id: switch.hzp
    - service: logbook.log
      data_template:
        name: HZP_Sommerbetrieb
        message: ein
#
  - alias: 'HZP Sommerbetrieb aus'
    initial_state: true
    trigger:
      - platform: time_pattern
        hours: '12'
        minutes: '15'
        seconds: '0'
    condition:
      - condition: time
        weekday:
         - sat
    action:
    - service: switch.turn_off
      entity_id: switch.hzp
    - service: logbook.log
      data_template:
        name: HZP_Sommerbetrieb
        message: aus
# Zeitschalter Sommerbetrieb ENDE ##############################################